// <auto-generated />
using System;
using BDRedSocial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDRedSocial.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20230904134019_redsocial1")]
    partial class redsocial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDRedSocial.Data.Entidades.CargoRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodCarRed")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("DescCargoRed")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CargosRed");
                });

            modelBuilder.Entity("BDRedSocial.Data.Entidades.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodPuesto")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("IdTrabajador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("BDRedSocial.Data.Entidades.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CargoRedId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PuestosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoRedId");

                    b.HasIndex("PuestosId");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("BDRedSocial.Data.Entidades.Trabajador", b =>
                {
                    b.HasOne("BDRedSocial.Data.Entidades.CargoRed", null)
                        .WithMany("Trabajadores")
                        .HasForeignKey("CargoRedId");

                    b.HasOne("BDRedSocial.Data.Entidades.Puesto", "Puestos")
                        .WithMany("Trabajadores")
                        .HasForeignKey("PuestosId");

                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("BDRedSocial.Data.Entidades.CargoRed", b =>
                {
                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("BDRedSocial.Data.Entidades.Puesto", b =>
                {
                    b.Navigation("Trabajadores");
                });
#pragma warning restore 612, 618
        }
    }
}
